name: Deploy Site on push
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get the latest code
      uses: actions/checkout@v4
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.CAMPAGNE_PROD_SERVER }} #CAMPAGNE_PROD_SERVER
        username: ${{ secrets.CAMPAGNE_PROD_USER }} #CAMPAGNE_PROD_USER
        password: ${{ secrets.CAMPAGNE_PROD_PASS}} #CAMPAGNE_PROD_PASS
        exclude: |
          ../../.git/
          ../../github/
          ../../README.md
          ../../LICENSE
          ../../node_modules/
          .../../package-lock.json
          .../../package.json
          ../../tailwind.config.js
          ../../Dockerfile
          ../../docker-compose.yml
          ../../.gitignore
          ../../.dockerignore
        rsync-options: --exclude=.git* --exclude=.git/ --exclude=README.md --exclude=readme.md --exclude=.gitignore
